version: '3.8'
networks:
  nginx-network:
    external: true
    name: nginx-network

services:
  Nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/test-projects/ftp-server/public/myuser:/var/ftp-server/public
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - nginx-network
    ports:
      - 80:80
      - 443:443

